# -*- coding: utf-8 -*-
"""interface_detection_billets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtAHVNdquwGR4ARV_X5uC1DUHDHHD6Rv
"""

# Installer Gradio
!pip install gradio -q

# Importer les bibliothèques nécessaires
import pandas as pd
import joblib
import gradio as gr

# Connecter Google Drive à Colab
from google.colab import drive
drive.mount('/content/drive')

# Charger le modèle Random Forest sauvegardé
modele = joblib.load(
    "/content/drive/MyDrive/Colab Notebooks/P12/modele_random_forest.pkl"
)

# Définir les caractéristiques utilisées pendant l'entraînement
features = [
    "diagonal",
    "height_left",
    "height_right",
    "margin_low",
    "margin_up",
    "length"
]

# Fonction utilisée par l'interface pour analyser un seul billet
def interface_billet(diagonal, height_left, height_right,
                     margin_low, margin_up, length):

    # Créer un DataFrame avec les 6 caractéristiques du billet
    billet = pd.DataFrame([[
        diagonal,
        height_left,
        height_right,
        margin_low,
        margin_up,
        length
    ]], columns=features)

    # Faire la prédiction
    prediction = modele.predict(billet)[0]

    # Calculer les probabilités
    probabilites = modele.predict_proba(billet)[0]

    # Préparer le résultat
    if prediction:
        nature = "Billet authentique"
    else:
        nature = "Faux billet"

    # Retourner un résultat lisible
    return (
        f"{nature}\n"
        f"Prédiction binaire : {int(prediction)}\n"
        f"Probabilité faux : {probabilites[0]:.2%}\n"
        f"Probabilité authentique : {probabilites[1]:.2%}"
    )

# Fonction utilisée par l'interface pour analyser plusieurs billets
# à partir d'un fichier CSV
def interface_csv(fichier):

    # Charger le fichier CSV sélectionné
    df_billets = pd.read_csv(fichier, sep=";")

    # Vérifier que toutes les colonnes nécessaires sont présentes
    colonnes_manquantes = [
        colonne for colonne in features
        if colonne not in df_billets.columns
    ]

    # Arrêter l'analyse si une colonne est absente
    if colonnes_manquantes:
        raise ValueError(
            f"Colonnes manquantes : {colonnes_manquantes}"
        )

    # Sélectionner les 6 caractéristiques dans le bon ordre
    X_nouveaux = df_billets[features]

    # Vérifier qu'il n'y a pas de valeurs manquantes
    if X_nouveaux.isna().any().any():
        raise ValueError(
            "Certaines caractéristiques sont manquantes."
        )

    # Faire les prédictions
    predictions = modele.predict(X_nouveaux)

    # Calculer les probabilités d'authenticité
    probabilites = modele.predict_proba(X_nouveaux)[:, 1]

    # Ajouter les résultats au tableau
    df_billets["prediction"] = predictions.astype(int)
    df_billets["probabilite_authentique"] = probabilites

    # Retourner le tableau à l'interface
    return df_billets

# Créer l'interface Gradio
with gr.Blocks() as application:

    # Titre de l'application
    gr.Markdown("# Détection automatique de faux billets")
    gr.Markdown(
        "Modèle Random Forest — 0 = faux billet, 1 = billet authentique"
    )

    # Onglet 1 : analyser un seul billet
    with gr.Tab("Analyser un billet"):

        diagonal = gr.Number(label="Diagonal")
        height_left = gr.Number(label="Height left")
        height_right = gr.Number(label="Height right")
        margin_low = gr.Number(label="Margin low")
        margin_up = gr.Number(label="Margin up")
        length = gr.Number(label="Length")

        # Bouton pour lancer la prédiction
        bouton_billet = gr.Button("Analyser le billet")

        # Zone où le résultat sera affiché
        resultat_billet = gr.Textbox(
            label="Résultat",
            lines=4
        )

        # Relier le bouton à la fonction interface_billet
        bouton_billet.click(
            fn=interface_billet,
            inputs=[
                diagonal,
                height_left,
                height_right,
                margin_low,
                margin_up,
                length
            ],
            outputs=resultat_billet
        )

    # Onglet 2 : analyser un fichier CSV
    with gr.Tab("Analyser un fichier CSV"):

        # Zone pour sélectionner un fichier CSV
        fichier_csv = gr.File(
            label="Sélectionner un fichier CSV",
            type="filepath"
        )

        # Bouton pour lancer l'analyse
        bouton_csv = gr.Button("Analyser le fichier")

        # Tableau contenant les résultats
        resultats_csv = gr.Dataframe(
            label="Résultats des prédictions"
        )

        # Relier le bouton à la fonction interface_csv
        bouton_csv.click(
            fn=interface_csv,
            inputs=fichier_csv,
            outputs=resultats_csv
        )

#lancer l'application
application.launch()